// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1DbHPvMFqajEJ2gEfuqPYQTnmsrx6kok',
    appId: '1:943788281636:web:3ee10127f27dea1aaa2db1',
    messagingSenderId: '943788281636',
    projectId: 'shop-a4886',
    authDomain: 'shop-a4886.firebaseapp.com',
    storageBucket: 'shop-a4886.appspot.com',
    measurementId: 'G-VK5YWR42DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB7-TfP3GlH-kx9MrTGwvV6Ehe8mCg98Y',
    appId: '1:943788281636:android:0a2b2d77c63f959caa2db1',
    messagingSenderId: '943788281636',
    projectId: 'shop-a4886',
    storageBucket: 'shop-a4886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4WYRiBefj9ar0N58h-0og8fl-IgLAs3I',
    appId: '1:943788281636:ios:b2f928c29af9cae8aa2db1',
    messagingSenderId: '943788281636',
    projectId: 'shop-a4886',
    storageBucket: 'shop-a4886.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4WYRiBefj9ar0N58h-0og8fl-IgLAs3I',
    appId: '1:943788281636:ios:b2f928c29af9cae8aa2db1',
    messagingSenderId: '943788281636',
    projectId: 'shop-a4886',
    storageBucket: 'shop-a4886.appspot.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1DbHPvMFqajEJ2gEfuqPYQTnmsrx6kok',
    appId: '1:943788281636:web:da0e827af9594000aa2db1',
    messagingSenderId: '943788281636',
    projectId: 'shop-a4886',
    authDomain: 'shop-a4886.firebaseapp.com',
    storageBucket: 'shop-a4886.appspot.com',
    measurementId: 'G-JEMQXDNB68',
  );
}
